os:
  - linux
  - osx
  
language: node_js

node_js:
  - "0.10"

before_install:
  - "cd assets"
  - "gem install compass"
  - "npm install grunt-cli bower -g"

before_script:
 - "npm install grunt-meta-excel"

script:
 - "npm test"
 - "grunt test"

