language: node_js

node_js:
  - "0.10"

before_install:
  - "cd assets"
  - "npm install grunt-cli bower -g"

before_script:
 - "npm install grunt-meta-excel"

script:
 - "grunt meta_excel::generate"
 - "grunt update_nav_excel"
 - "npm test"

